name: Deploy to Production

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    
    env:
      PROJECT: ${{ vars.PROJECT }}
      PROJECT_ID: ${{ vars.PROJECT_ID }}
      REGION: ${{ vars.REGION }}
      ARTIFACTSREPO: ${{ vars.ARTIFACTSREPO }}
      MEMORY: ${{ vars.MEMORY }}
      TAG: ${{ github.ref_name }}

    steps:
    - uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    # First run only. 
    #- name: Configure Docker for Artifact Registry
    #  run: make cloud_init

    - name: Build and push API
      run: |
        make cloud_build SERVICE=api TAG=${{ github.ref_name }}
        make cloud_push SERVICE=api TAG=${{ github.ref_name }}

    - name: Build and push APP
      run: |
        make cloud_build SERVICE=app TAG=${{ github.ref_name }}
        make cloud_push SERVICE=app TAG=${{ github.ref_name }}

    - name: Deploy API to Cloud Run
      run: make cloud_deploy SERVICE=api MEMORY=${{ env.MEMORY }} TAG=${{ github.ref_name }}

    - name: Deploy APP to Cloud Run
      run: make cloud_deploy SERVICE=app MEMORY=${{ env.MEMORY }} TAG=${{ github.ref_name }}